# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d06da716f35bb3e57f9b8486fabe9b6a51de4e454b9b301eccdff31cb806714df3c9f4f12d6e7083a8a209c46822beb3df7d668049f21a708a20dc1deaa2b188

test:
  secret_key_base: 38bc305d4db64755bcbd601d52e907514e183db0f944933e9cbe2abebdf549681e44dbe8b3b37b4aa79bfb1544f86f4cb66c581a1ad8d1ce1d33f53c56c49141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
